# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ef2f989764c765bc272ee51f04db881c834de939c6dca8dd250182af21149677fba29cfe2186e287e4762b5bb1a7db87514d50fab66b1305cde164ef4d08a3

test:
  secret_key_base: 98d7fcaa3a110d95f3d948d3c56085ebff17f48017afe8a7c2fc6d864935f98bf860e7dc0748ec4f2d855e97d889cddd79e0d070232f77d16d4b8a66867dad41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
